import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { client } from "@/libs/client";
import { Blog, Tag } from "@/types/blog";
import Link from "next/link";
import { Category } from "@/types/category";
import { BlogCard } from "@/components/BlogCard/BlogCard";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  blogs: Array<Blog>;
  categories: Array<Category>;
  tags: Array<Tag>;
};

export default function Home({ blogs, categories, tags }: Props) {
  //console.log(blogs);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <main className={styles.main}>
          {/* <ul>
          {categories.map((category) => (
            <li key={category.id}>
              <Link href={`/categories/${category.id}`}>{category.name}</Link>
            </li>
          ))}
        </ul> */}

          <ul>
            {blogs.map((blog) => {
              return <BlogCard blog={blog} key={blog.id} />;
            })}
          </ul>
        </main>
        <section className={styles.side}>
          <p className={styles.tagsTitle}>#Tags</p>
          <ul>
            {tags.map((tag) => (
              <li key={tag.id}>
                <Link href={`/tags/${tag.id}`}>{tag.name}</Link>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blogs" });
  const tagData = await client.get({ endpoint: "tags" });
  const categoryData = await client.get({ endpoint: "categories" });
  return {
    props: {
      blogs: data.contents,
      categories: categoryData.contents,
      tags: tagData.contents,
    },
  };
};
